# Default values for teamcity.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: zeppelinux/ninjam-server
  tag: v0.080
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 2049

# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
#  limits:
#    cpu: 800m
#    memory: 968Mi
#  requests:
#    cpu: 600m
#    memory: 968Mi

nodeSelector: {}

tolerations: []

affinity: {}
